name: hds_stoch
channels:
  - conda-forge
dependencies:
  - joblib=1.1.0
  - jupyterlab=3.2.4
  - jupyterlab-spellchecker=0.7.2
  - matplotlib=3.5.0
  - numpy=1.21.4
  - pandas=1.3.4
  - pip=20.1.1
  - python=3.8.8
  - scikit-learn=1.0.1
  - scipy=1.7.3
  - seaborn=0.11.1
  - pip:
    - simpy==4.0.1

