name: hds_stoch
channels:
  - defaults
dependencies:
  - joblib=0.15.1
  - jupyterlab=2.1.5
  - matplotlib=3.2.2
  - nodejs=10.13.0
  - numpy=1.18.5
  - pandas=1.0.5
  - pip=20.1.1
  - python=3.7.7
  - scipy=1.5.0
  - seaborn=0.10.0
  - pip:
    - scikit-learn==0.23.0
    - simpy==4.0.1

